"""Policy values for per-API-key rate limiting."""

RATE_LIMIT_CAPACITY = 10
RATE_LIMIT_REFILL_PER_MIN = 20
RATE_LIMIT_TTL_S = 3600
TOKEN_RATE_LIMIT_CAPACITY = 20_000
TOKEN_RATE_LIMIT_REFILL_PER_MIN = 20_000
MAX_INPUT_TOKENS = 8_192
