"""ORM models. Alembic autogenerate imports this module, so every table must land here.

Table names carry a domain prefix (money_transactions, task_items) and every
user-owned table carries user_id, even while the app has a single user.
Datetimes are stored UTC.
"""

from datetime import datetime

from sqlalchemy import (
    CHAR,
    BigInteger,
    Boolean,
    CheckConstraint,
    ForeignKey,
    Index,
    Integer,
    String,
)
from sqlalchemy.orm import Mapped, mapped_column

from app.db import Base

__all__ = [
    "ApiKey",
    "ApiKeyAuditLog",
    "AuthFailureLog",
    "Base",
    "LlmModel",
    "LlmQuota",
    "LlmUsageLog",
    "User",
]

API_KEY_STATUSES = ("active", "revoked", "deleted")
USAGE_SOURCES = ("api", "web")


class User(Base):
    """This service's mirror of the main application's user id.

    Holds no profile data: identity lives in the main application. The row
    exists so identity tables can carry a real foreign key, and it doubles as
    the per-user lock that serialises API key creation.
    """

    __tablename__ = "identity_users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=False)


class ApiKey(Base):
    __tablename__ = "identity_api_keys"
    __table_args__ = (
        CheckConstraint(
            "status IN ('active', 'revoked', 'deleted')",
            name="ck_identity_api_keys_status",
        ),
        Index("ix_identity_api_keys_user_id_status", "user_id", "status"),
    )

    # ULID, generated by the app. validate_api_key rejects any key id that is
    # not a ULID, so an autoincrement int here would make every key fail.
    id: Mapped[str] = mapped_column(String(26), primary_key=True)
    # Indexed by ix_identity_api_keys_user_id_status, whose leading column
    # also serves the foreign key.
    user_id: Mapped[int] = mapped_column(
        ForeignKey("identity_users.id"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    # SHA-256 hex of the secret. The secret itself is never stored.
    key_hash: Mapped[str] = mapped_column(CHAR(64), nullable=False, unique=True)
    # The only source of truth for validity. revoked_at / deleted_at are audit.
    status: Mapped[str] = mapped_column(String(10), nullable=False)
    created_at: Mapped[datetime] = mapped_column(nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column()
    deleted_at: Mapped[datetime | None] = mapped_column()
    last_used_at: Mapped[datetime | None] = mapped_column()


class ApiKeyAuditLog(Base):
    """Append-only: the app's DB user has INSERT but no UPDATE/DELETE here."""

    __tablename__ = "identity_api_key_audit_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("identity_users.id"), nullable=False, index=True
    )  # owner of the key
    action: Mapped[str] = mapped_column(
        String(32), nullable=False
    )  # key.created | key.revoked | key.deleted
    actor_id: Mapped[int | None] = mapped_column(Integer)  # null for "system"
    actor_type: Mapped[str] = mapped_column(
        String(16), nullable=False
    )  # owner | admin | system
    target_type: Mapped[str] = mapped_column(String(32), nullable=False)
    # Without it a row says a key was revoked but not which one.
    target_id: Mapped[str] = mapped_column(String(26), nullable=False, index=True)
    request_id: Mapped[str | None] = mapped_column(String(64), index=True)
    source_ip: Mapped[str | None] = mapped_column(String(45))
    # Indexed for the retention job, which deletes by age.
    created_at: Mapped[datetime] = mapped_column(nullable=False, index=True)


class AuthFailureLog(Base):
    """Failed API key authentications. Append-only, like the audit log.

    Kept apart from ApiKeyAuditLog on purpose: the key id here comes from an
    unauthenticated caller, so it may not exist and cannot carry a user_id or
    foreign key, and an attacker controls how fast this table grows.
    """

    __tablename__ = "identity_auth_failure_logs"

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    action: Mapped[str] = mapped_column(String(32), nullable=False)  # auth.failed
    key_id: Mapped[str] = mapped_column(String(26), nullable=False, index=True)
    source_ip: Mapped[str] = mapped_column(String(45), nullable=False, index=True)
    reason: Mapped[str] = mapped_column(String(32), nullable=False)
    created_at: Mapped[datetime] = mapped_column(nullable=False, index=True)


# region llm — TODO(chat-pipeline): shape agreed provisionally; confirm with the
# chat pipeline owner before this migration runs anywhere shared.
class LlmModel(Base):
    __tablename__ = "llm_models"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    name: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    # The model's total window. Deliberately not called max_tokens: in a chat
    # request max_tokens is the output cap, and sharing the name invites
    # setting the output cap to the whole window.
    context_window: Mapped[int] = mapped_column(Integer, nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="1")


class LlmQuota(Base):
    __tablename__ = "llm_quotas"

    user_id: Mapped[int] = mapped_column(
        ForeignKey("identity_users.id"), primary_key=True, autoincrement=False
    )
    token_limit: Mapped[int] = mapped_column(BigInteger, nullable=False)
    token_used: Mapped[int] = mapped_column(
        BigInteger, nullable=False, server_default="0"
    )


class LlmUsageLog(Base):
    """Append-only. Retained USAGE_RETENTION_DAYS (app/constants/retention.py)."""

    __tablename__ = "llm_usage_logs"
    __table_args__ = (
        CheckConstraint("source IN ('api', 'web')", name="ck_llm_usage_logs_source"),
        Index("ix_llm_usage_logs_user_id_created_at", "user_id", "created_at"),
    )

    id: Mapped[int] = mapped_column(BigInteger, primary_key=True, autoincrement=True)
    user_id: Mapped[int] = mapped_column(
        ForeignKey("identity_users.id"), nullable=False
    )
    # Where the call came from, so a user can see why a shared quota ran out.
    source: Mapped[str] = mapped_column(String(8), nullable=False)
    # Null for web usage. No FK: usage outlives the key it was billed to.
    key_id: Mapped[str | None] = mapped_column(String(26), index=True)
    model: Mapped[str] = mapped_column(String(64), nullable=False)
    prompt_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    completion_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    total_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    # (user_id, created_at) serves the dashboard; this one serves retention,
    # which deletes by age across all users.
    created_at: Mapped[datetime] = mapped_column(nullable=False, index=True)


# endregion
